using System.Runtime.InteropServices;

namespace XashGameDLL;

[StructLayout(LayoutKind.Sequential)]
public unsafe struct EngineFuncs
{
    public delegate* unmanaged[Cdecl]<IntPtr, int> pfnPrecacheModel;
public delegate* unmanaged[Cdecl]<IntPtr, int> pfnPrecacheSound;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr, void> pfnSetModel;
public delegate* unmanaged[Cdecl]<IntPtr, int> pfnModelIndex;
public delegate* unmanaged[Cdecl]<int, int> pfnModelFrames;
public delegate* unmanaged[Cdecl]<Edict*, float*, float*, void> pfnSetSize;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, void> pfnChangeLevel;
public delegate* unmanaged[Cdecl]<Edict*, void> pfnGetSpawnParms;
public delegate* unmanaged[Cdecl]<Edict*, void> pfnSaveSpawnParms;
public delegate* unmanaged[Cdecl]<float*, float> pfnVecToYaw;
public delegate* unmanaged[Cdecl]<float*, float*, float*, void> pfnVecToAngles;
public delegate* unmanaged[Cdecl]<Edict*, float*, float, int, void> pfnMoveToOrigin;
public delegate* unmanaged[Cdecl]<Edict*, void> pfnChangeYaw;
public delegate* unmanaged[Cdecl]<Edict*, void> pfnChangePitch;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr, IntPtr, Edict*> pfnFindEntityByString;
public delegate* unmanaged[Cdecl]<Edict*, int> pfnGetEntityIllum;
public delegate* unmanaged[Cdecl]<Edict*, float*, float, Edict*> pfnFindEntityInSphere;
public delegate* unmanaged[Cdecl]<Edict*, Edict*> pfnFindClientInPVS;
public delegate* unmanaged[Cdecl]<Edict*, Edict*> pfnEntitiesInPVS;
public delegate* unmanaged[Cdecl]<float*, void> pfnMakeVectors;
public delegate* unmanaged[Cdecl]<float*, float*, float*, float*, void> pfnAngleVectors;
public delegate* unmanaged[Cdecl]<void> pfnCreateEntity;
public delegate* unmanaged[Cdecl]<Edict*, void> pfnRemoveEntity;
public delegate* unmanaged[Cdecl]<int, Edict*> pfnCreateNamedEntity;
public delegate* unmanaged[Cdecl]<Edict*, void> pfnMakeStatic;
public delegate* unmanaged[Cdecl]<Edict*, int> pfnEntIsOnFloor;
public delegate* unmanaged[Cdecl]<Edict*, int> pfnDropToFloor;
public delegate* unmanaged[Cdecl]<Edict*, float, float, int, int> pfnWalkMove;
public delegate* unmanaged[Cdecl]<Edict*, float*, void> pfnSetOrigin;
public delegate* unmanaged[Cdecl]<Edict*, int, IntPtr, float, float, int, int, void> pfnEmitSound;
public delegate* unmanaged[Cdecl]<Edict*, float*, IntPtr, float, float, int, int, void> pfnEmitAmbientSound;
    //public delegate* unmanaged[Cdecl]<float*, float*, int, Edict*, TraceResult*, void> pfnTraceLine;
    private IntPtr TempVariable1;
//public delegate* unmanaged[Cdecl]<Edict*, Edict*, TraceResult*, void> pfnTraceToss;
    private IntPtr TempVariable2;
//public delegate* unmanaged[Cdecl]<Edict*, float*, float*, int, Edict*, TraceResult*, int> pfnTraceMonsterHull;
//public delegate* unmanaged[Cdecl]<float*, float*, int, int, Edict*, TraceResult*, void> pfnTraceHull;
//public delegate* unmanaged[Cdecl]<float*, float*, int, Edict*, TraceResult*, void> pfnTraceModel;
    private IntPtr TempVariable3;
    private IntPtr TempVariable4;
    private IntPtr TempVariable5;
public delegate* unmanaged[Cdecl]<Edict*, float*, float*, IntPtr> pfnTraceTexture;
//public delegate* unmanaged[Cdecl]<float*, float*, int, float, Edict*, TraceResult*, void> pfnTraceSphere;
private IntPtr TempVariable6;
public delegate* unmanaged[Cdecl]<Edict*, float, float*, void> pfnGetAimVector;
public delegate* unmanaged[Cdecl]<IntPtr, void> pfnServerCommand;
public delegate* unmanaged[Cdecl]<void> pfnServerExecute;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr, void> pfnClientCommand; // Note: variadic in C, no direct support in C#
public delegate* unmanaged[Cdecl]<float*, float*, float, float, void> pfnParticleEffect;
public delegate* unmanaged[Cdecl]<int, IntPtr, void> pfnLightStyle;
public delegate* unmanaged[Cdecl]<IntPtr, int> pfnDecalIndex;
public delegate* unmanaged[Cdecl]<float*, int> pfnPointContents;
public delegate* unmanaged[Cdecl]<int, int, float*, Edict*, void> pfnMessageBegin;
public delegate* unmanaged[Cdecl]<void> pfnMessageEnd;
public delegate* unmanaged[Cdecl]<int, void> pfnWriteByte;
public delegate* unmanaged[Cdecl]<int, void> pfnWriteChar;
public delegate* unmanaged[Cdecl]<int, void> pfnWriteShort;
public delegate* unmanaged[Cdecl]<int, void> pfnWriteLong;
public delegate* unmanaged[Cdecl]<float, void> pfnWriteAngle;
public delegate* unmanaged[Cdecl]<float, void> pfnWriteCoord;
public delegate* unmanaged[Cdecl]<IntPtr, void> pfnWriteString;
public delegate* unmanaged[Cdecl]<int, void> pfnWriteEntity;
//public delegate* unmanaged[Cdecl]<cvar_t*, void> pfnCVarRegister;
    private IntPtr TempVariable7;
public delegate* unmanaged[Cdecl]<IntPtr, float> pfnCVarGetFloat;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr> pfnCVarGetString;
public delegate* unmanaged[Cdecl]<IntPtr, float, void> pfnCVarSetFloat;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, void> pfnCVarSetString;
//public delegate* unmanaged[Cdecl]<ALERT_TYPE, IntPtr, void> pfnAlertMessage;
    private IntPtr TempVariable8;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, void> pfnEngineFprintf;
public delegate* unmanaged[Cdecl]<Edict*, int, void*> pfnPvAllocEntPrivateData;
public delegate* unmanaged[Cdecl]<Edict*, void*> pfnPvEntPrivateData;
public delegate* unmanaged[Cdecl]<Edict*, void> pfnFreeEntPrivateData;
public delegate* unmanaged[Cdecl]<int, IntPtr> pfnSzFromIndex;
public delegate* unmanaged[Cdecl]<IntPtr, int> pfnAllocString;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr> pfnGetVarsOfEnt;
public delegate* unmanaged[Cdecl]<int, Edict*> pfnPEntityOfEntOffset;
public delegate* unmanaged[Cdecl]<Edict*, int> pfnEntOffsetOfPEntity;
public delegate* unmanaged[Cdecl]<Edict*, int> pfnIndexOfEdict;
public delegate* unmanaged[Cdecl]<int, Edict*> pfnPEntityOfEntIndex;
public delegate* unmanaged[Cdecl]<IntPtr, Edict*> pfnFindEntityByVars;
public delegate* unmanaged[Cdecl]<Edict*, void*> pfnGetModelPtr;
public delegate* unmanaged[Cdecl]<IntPtr, int, int> pfnRegUserMsg;
public delegate* unmanaged[Cdecl]<Edict*, float, void> pfnAnimationAutomove;
public delegate* unmanaged[Cdecl]<Edict*, int, float*, float*, void> pfnGetBonePosition;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr> pfnFunctionFromName;
public delegate* unmanaged[Cdecl]<void*, IntPtr> pfnNameForFunction;
//public delegate* unmanaged[Cdecl]<Edict*, PRINT_TYPE, IntPtr, void> pfnClientPrintf;
private IntPtr TempVariable9;
public delegate* unmanaged[Cdecl]<IntPtr, void> pfnServerPrint;
public delegate* unmanaged[Cdecl]<IntPtr> pfnCmd_Args;
public delegate* unmanaged[Cdecl]<int, IntPtr> pfnCmd_Argv;
public delegate* unmanaged[Cdecl]<int> pfnCmd_Argc;
public delegate* unmanaged[Cdecl]<Edict*, int, float*, float*, void> pfnGetAttachment;
//public delegate* unmanaged[Cdecl]<CRC32_t*, void> pfnCRC32_Init;
//public delegate* unmanaged[Cdecl]<CRC32_t*, void*, int, void> pfnCRC32_ProcessBuffer;
//public delegate* unmanaged[Cdecl]<CRC32_t*, byte, void> pfnCRC32_ProcessByte;
//public delegate* unmanaged[Cdecl]<CRC32_t, CRC32_t> pfnCRC32_Final;
    private IntPtr TempVariable10;
    private IntPtr TempVariable11;
    private IntPtr TempVariable12;
    private IntPtr TempVariable13;
public delegate* unmanaged[Cdecl]<int, int, int> pfnRandomLong;
public delegate* unmanaged[Cdecl]<float, float, float> pfnRandomFloat;
public delegate* unmanaged[Cdecl]<Edict*, Edict*, void> pfnSetView;
public delegate* unmanaged[Cdecl]<float> pfnTime;
public delegate* unmanaged[Cdecl]<Edict*, float, float, void> pfnCrosshairAngle;
public delegate* unmanaged[Cdecl]<IntPtr, int*, byte*> pfnLoadFileForMe;
public delegate* unmanaged[Cdecl]<void*, void> pfnFreeFile;
public delegate* unmanaged[Cdecl]<IntPtr, void> pfnEndSection;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, int*, int> pfnCompareFileTime;
public delegate* unmanaged[Cdecl]<IntPtr, void> pfnGetGameDir;
//public delegate* unmanaged[Cdecl]<cvar_t*, void> pfnCvar_RegisterVariable;
private IntPtr TempVariable14;
public delegate* unmanaged[Cdecl]<Edict*, int, int, int, int, void> pfnFadeClientVolume;
public delegate* unmanaged[Cdecl]<Edict*, float, void> pfnSetClientMaxspeed;
public delegate* unmanaged[Cdecl]<IntPtr, Edict*> pfnCreateFakeClient;
public delegate* unmanaged[Cdecl]<Edict*, float*, float, float, float, ushort, byte, byte, void> pfnRunPlayerMove;
public delegate* unmanaged[Cdecl]<int> pfnNumberOfEntities;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr> pfnGetInfoKeyBuffer;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, IntPtr> pfnInfoKeyValue;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, IntPtr, void> pfnSetKeyValue;
public delegate* unmanaged[Cdecl]<int, IntPtr, IntPtr, IntPtr, void> pfnSetClientKeyValue;
public delegate* unmanaged[Cdecl]<IntPtr, int> pfnIsMapValid;
public delegate* unmanaged[Cdecl]<float*, int, int, int, void> pfnStaticDecal;
public delegate* unmanaged[Cdecl]<IntPtr, int> pfnPrecacheGeneric;
public delegate* unmanaged[Cdecl]<Edict*, int> pfnGetPlayerUserId;
public delegate* unmanaged[Cdecl]<Edict*, int, IntPtr, float, float, int, int, int, int, void> pfnBuildSoundMsg;
public delegate* unmanaged[Cdecl]<int> pfnIsDedicatedServer;
//public delegate* unmanaged[Cdecl]<IntPtr, cvar_t*> pfnCVarGetPointer;
private IntPtr TempVariable15;
public delegate* unmanaged[Cdecl]<Edict*, uint> pfnGetPlayerWONId;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, void> pfnInfo_RemoveKey;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr, IntPtr> pfnGetPhysicsKeyValue;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr, IntPtr, void> pfnSetPhysicsKeyValue;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr> pfnGetPhysicsInfoString;
public delegate* unmanaged[Cdecl]<int, IntPtr, ushort> pfnPrecacheEvent;
public delegate* unmanaged[Cdecl]<int, Edict*, ushort, float, float*, float*, float, float, int, int, int, int, void> pfnPlaybackEvent;
public delegate* unmanaged[Cdecl]<float*, byte*> pfnSetFatPVS;
public delegate* unmanaged[Cdecl]<float*, byte*> pfnSetFatPAS;
public delegate* unmanaged[Cdecl]<Edict*, byte*, int> pfnCheckVisibility;
public delegate* unmanaged[Cdecl]<Delta*, IntPtr, void> pfnDeltaSetField;
public delegate* unmanaged[Cdecl]<Delta*, IntPtr, void> pfnDeltaUnsetField;
public delegate* unmanaged[Cdecl]<IntPtr, delegate* unmanaged[Cdecl]<Delta*, byte*, byte*, void>, void> pfnDeltaAddEncoder;
public delegate* unmanaged[Cdecl]<int> pfnGetCurrentPlayer;
public delegate* unmanaged[Cdecl]<Edict*, int> pfnCanSkipPlayer;
public delegate* unmanaged[Cdecl]<Delta*, IntPtr, int> pfnDeltaFindField;
public delegate* unmanaged[Cdecl]<Delta*, int, void> pfnDeltaSetFieldByIndex;
public delegate* unmanaged[Cdecl]<Delta*, int, void> pfnDeltaUnsetFieldByIndex;
public delegate* unmanaged[Cdecl]<int, int, void> pfnSetGroupMask;
//public delegate* unmanaged[Cdecl]<int, entity_state_s*, int> pfnCreateInstancedBaseline;
//public delegate* unmanaged[Cdecl]<cvar_s*, IntPtr, void> pfnCvar_DirectSet;
//public delegate* unmanaged[Cdecl]<FORCE_TYPE, float*, float*, IntPtr, void> pfnForceUnmodified;
    private IntPtr TempVariable23;
    private IntPtr TempVariable24;
    private IntPtr TempVariable25;
public delegate* unmanaged[Cdecl]<Edict*, int*, int*, void> pfnGetPlayerStats;
public delegate* unmanaged[Cdecl]<IntPtr, delegate* unmanaged[Cdecl]<void>, void> pfnAddServerCommand;
public delegate* unmanaged[Cdecl]<int, int, int> pfnVoice_GetClientListening;
public delegate* unmanaged[Cdecl]<int, int, int, int> pfnVoice_SetClientListening;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr> pfnGetPlayerAuthId;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, void*> pfnSequenceGet;
public delegate* unmanaged[Cdecl]<IntPtr, int, int*, void*> pfnSequencePickSentence;
public delegate* unmanaged[Cdecl]<IntPtr, int> pfnGetFileSize;
public delegate* unmanaged[Cdecl]<IntPtr, uint> pfnGetApproxWavePlayLen;
public delegate* unmanaged[Cdecl]<int> pfnIsCareerMatch;
public delegate* unmanaged[Cdecl]<IntPtr, int> pfnGetLocalizedStringLength;
public delegate* unmanaged[Cdecl]<int, void> pfnRegisterTutorMessageShown;
public delegate* unmanaged[Cdecl]<int, int> pfnGetTimesTutorMessageShown;
public delegate* unmanaged[Cdecl]<int*, int, void> pfnProcessTutorMessageDecayBuffer;
public delegate* unmanaged[Cdecl]<int*, int, void> pfnConstructTutorMessageDecayBuffer;
public delegate* unmanaged[Cdecl]<void> pfnResetTutorMessageDecayData;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr, void> pfnQueryClientCvarValue;
public delegate* unmanaged[Cdecl]<Edict*, IntPtr, int, void> pfnQueryClientCvarValue2;
public delegate* unmanaged[Cdecl]<IntPtr, IntPtr, int> pfnCheckParm;
public delegate* unmanaged[Cdecl]<int, Edict*> pfnPEntityOfEntIndexAllEntities;

    internal static EngineFuncs* Funcs;
}