<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PublishAot>true</PublishAot>
        <OutputType>Library</OutputType>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <NativeLib>Shared</NativeLib>
        <EnableDynamicLoading>false</EnableDynamicLoading>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DefineConstants>TRACE X64</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DefineConstants>TRACE X64</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\HalfLifeCommon\HalfLifeCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="..\EntitiesGeneratedFiles\EntityGenerator\EntityGenerator.EntityGenerator\ServerEntities.g.cs">
        <Link>Generated\ServerEntities.g.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
